### PR TITLE
New gradle, new play services, replace BIND_LISTENER

### PR DESCRIPTION
**Pull request by matejdro**
Modernizing the library, allowing it to build with latest play services and to be used alongside other wear listener services.

### CODE REVIEW

**Comment by tajchert** [comment]
Did you test it and it works properly? Sorry but currently don't have a Wear to easy test this.

**Comment by matejdro** [comment]
Yes, I did. Example app works fine.

**Comment by tajchert** [comment]
Thanks!

**Comment by tajchert** [comment]
I will later update version of a library, probably with jitpack.io to speed things up

**Comment by matejdro** [comment]
Any chance you could push this new version to maven?

**Pull request merged**
